#!/bin/sh

# Parse command line arguments
VALID_ARGS=$(getopt -o s:o:f:u:: --long schedule:,overrides:,from:,until: -- "$@")

# Error Handling for getopt
if [ $? -ne 0 ]; then
    exit 1;
fi

usage(){
    echo "Usage: $0 --schedule <schedule_file> --overrides <overrides_file> --from <from_time> --until <until_time>"
    exit 1
}

# Parse the command line arguments
eval set -- "$VALID_ARGS"
while :
do
  case "$1" in
    -s | --schedule)
        SCHEDULE_FILE=$2
        shift 2
        ;;
    -o | --overrides)
        OVERRIDES_FILE=$2
        shift 2
        ;;
    -f | --from)
        FROM_DATE=$2
        shift 2
        ;;
    -u | --until)
        UNTIL_DATE=$2
        shift 2
        ;;
    --) shift; break ;;
    *) echo "Unsupported option: $1"
       usage ;;
  esac
done

if [ -z "$SCHEDULE_FILE" ] || [ -z "$OVERRIDES_FILE" ] || [ -z "$FROM_DATE" ] || [ -z "$UNTIL_DATE" ]; then
    usage
fi

# Run Python3 script with arguments
python3 ./render-schedule.py --schedule_="$SCHEDULE_FILE" --overrides_="$OVERRIDES_FILE" --from_="$FROM_DATE" --until_="$UNTIL_DATE"